name: Deploy NPM package

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Deploy NPM package
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm install
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Update package.json version
        run: |
          npm version ${{ steps.get_version.outputs.version }} --no-git-tag-version
      - name: Deploy to NPM Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}