name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    timeout-minutes: 10
    name: Node v${{ matrix.node-version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 17.x, 18.x, 19.x, 20.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set git config
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
        if: runner.os == 'Windows'
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #latest v4. TODO upgrade
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d #latest  v3. TODO upgrade
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create the npm cache directory
        run: mkdir npm-cache && npm config set cache ./npm-cache --global
      - name: Cache node modules
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 #latest v3 TODO upgrade
        with:
          path: ./npm-cache
          key: v1-${{ runner.os }}-node-${{ matrix.node-version }}-npm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            v1-${{ runner.os }}-node-${{ matrix.node-version }}-npm-
      - run: npm install
      - run: npm test
        env:
          CI: true

  benchmark:
    timeout-minutes: 15
    name: Measure performance impact of changes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #latest v4. TODO upgrade
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d #latest  v3. TODO upgrade
        with:
          node-version: 18
      - name: Create the npm cache directory
        run: mkdir npm-cache && npm config set cache ./npm-cache --global
      - name: Cache node modules
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 #latest v3 TODO upgrade
        with:
          path: ./npm-cache
          key: v1-npm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            v1-npm-
      - run: npm install
      - run: npm run benchmark
        env:
          CI: true

  typescript:
    timeout-minutes: 15
    name: Ensure typescript compatibility
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #latest v4. TODO upgrade
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d #latest  v3. TODO upgrade
        with:
          node-version: 18
      - name: Create the npm cache directory
        run: mkdir npm-cache && npm config set cache ./npm-cache --global
      - name: Cache node modules
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 #latest v3 TODO upgrade
        with:
          path: ./npm-cache
          key: v1-npm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            v1-npm-
      - run: npm install
      - run: npm install typescript
      - run: tsc index.d.ts
        env:
          CI: true
