name: CI/CD

on:
  push:
    branches: [ master, "renovate/*" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    if: "!startsWith(github.ref, 'refs/tags/')"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test
        env:
          CI: true

  benchmark:
    if: "!startsWith(github.ref, 'refs/tags/')"
    timeout-minutes: 15
    name: Measure performance impact of changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - run: npm ci
      - run: npm run benchmark
        env:
          CI: true

  typescript:
    if: "!startsWith(github.ref, 'refs/tags/')"
    timeout-minutes: 15
    name: Ensure typescript compatibility
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - run: npm ci
      - run: tsc index.d.ts
        env:
          CI: true

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
